#!node --no-warnings
"use strict"

// - [x] io.serve
// - [x] io.fetch
// - [ ] moa test
// - [ ] moa repl
// - [ ] io.db
// - [ ] io.go.fmt.Println
// - [ ] integrate Go packages with type definition of Moa
// - [ ] moa env
// - [ ] package manager for Moa
// - [ ] io.c
// - [ ] io.js

const log = x => { console.dir(x, {depth: null}); return x }
const range = n => [...new Array(n)].map((_, i) => i)

const newtoken = (s, filename, lineno=0, column=0) => (m => m ? ({code: m[1], mark: m[2], filename, lineno, column}) : ({code: s, filename, lineno, column}))(s.match(/^([A-Za-z_].*)([?*])$/))

const sugar = (program, filename="") => {
  function* tokenize() {
    let pos = 0
    let lineno = 1
    let column = 0
    let indent = 0
    for (const code of program.split(/([A-Za-z_][A-Za-z0-9_]*[?*]?|-?0x[A-Fa-f0-9]+|-?[0-9]+(?:(?:\.[0-9]+)|(?:e[0-9]+))?|""".*?"""|"[^"]*?"|```.*?```|`[^`]*?`|[ \r\n\t]+|[()\[\]{};]|#[^\n]*)/)) {
      if (/^[ \r\n\t#;]/.test(code) || code === "") {
        lineno += code.split(/\n|;/).length - 1
        if (code.includes("\n")) {
          indent = code.split(/\n/).at(-1).length
        }
      } else {
        const op = /^[+\-*/%|&<>=!]+$/.test(code) && code !== "=>"
        const lc = pos > 0 ? program[pos - 1] : ''
        const rc = program[pos + code.length]
        const op1 = op && /[A-Za-z0-9_\]]/.test(rc)
        const op2 = op && !op1
        const call = code === "(" && /[A-Za-z0-9_\]]/.test(lc)
        const index = code === "[" && /[A-Za-z0-9_\]]/.test(lc)
        yield {code, lineno, op, op1, op2, call, index, indent, filename, lineno, column}
      }
      pos += code.length
      column = code.includes("\n") ? code.split(/\n/).at(-1).length : column + code.length
    }
  }
  const compose = tokens => {
    let pos = 0
    const until = (f, g=bottom) => [...function*() { while (pos < tokens.length && f(tokens[pos])) { yield g() } }()]
    const faketoken = (s, t) => newtoken(s, filename, t.lineno, t.column)
    const isexp = x => !Array.isArray(x) || x[0].code !== "do"
    const untilby = by => (t => (pos++, t))(until(t => t.code !== by))
    const bottom = () => {
      const totoken = o => Array.isArray(o) ? totoken(o[0]) : o
      const comma = a => pos >= tokens.length ? a :
        tokens[pos].code === "," ? (pos++, comma(a.concat([tokens[pos++]]))) : a
      const addreturn = x => isexp(x) ? x : [...x.slice(0, -1), [faketoken("return", totoken(x)), x.at(-1)]]
      const block = t => t.lineno === tokens[pos].lineno ? line() :
        squash(until(u => u.indent > t.indent, line), a => [faketoken("do", t), ...a])
      const link = t =>
        pos >= tokens.length ? t :
        tokens[pos].code === "."  ? link([tokens[pos++], t, tokens[pos++]]) :
        tokens[pos].code === ","  ? link(comma([t])) :
        tokens[pos].code === "=>" ? (pos++, link([faketoken("fn", tokens[pos-1]), ...(Array.isArray(t) ? t : [t]), addreturn(block(tokens[pos-1]))])) :
        tokens[pos].call          ? (pos++, link([t].concat(untilby(")")))) :
        tokens[pos].index         ? (pos++, link([[faketoken(".", t), t, faketoken("at", t)]].concat([squash(variadic(untilby("]")))]))) :
        tokens[pos].op2           ? link([tokens[pos++], t, bottom()]) :
        t
      const t = tokens[pos++]
      return t.code === ":" ? block(t) :
             t.code === "(" ? variadic(untilby(")")) :
             t.op1          ? link([t, bottom()]) :
             link(t)
    }
    const line = () => (t => squash(variadic(until(u => t.lineno === u.lineno))))(tokens[pos])
    const top = () => until(_ => true, line)
    const squash = (a, f=x=>x) => a.length === 1 ? a[0] : f(a)
    const variadic = ([head, ...a]) => {
      const fail = x => { throw new Error(`never reach bug '${JSON.stringify(x)}'`) }
      const vop = (op, a) => [op, a[0], a.length === 2 ? a[1] : vop(op, a.slice(1))]
      const viif = (head, a) => [head, a[0], a[1], a.length === 3 ? a[2] : viif(head, a.slice(2))]
      const vif = (head, a) =>
        a.length >= 5 ? [head, a[0], a[1], vif(head, a.slice(2))] :
        a.length >= 4 ? [head, a[0], [head, ...a.slice(1)]] :
        [head, ...a]
      const t_ = faketoken("_", head)
      const t0 = faketoken("0", head)
      const t1 = faketoken("1", head)
      return head.op && a.length >= 3 ? vop(head, a) :
        head.code === "iif" ? viif(head, a) :
        head.code === "if"  ? vif(head, a) :
        head.code === "for" ? (
          a.length === 2 ? [head, t_,   t0,   a[0], t1, a[1]] :
          a.length === 3 ? [head, a[0], t0,   a[1], t1, a[2]] :
          a.length === 4 ? [head, a[0], a[1], a[2], t1, a[3]] :
          a.length === 5 ? [head, ...a] :
          fail(a)
        ) :
        head.code === "each" ? (
          a.length === 3 ? [head, t_, ...a] :
          a.length === 4 ? [head, ...a] :
          fail(a)
        ) :
        [head, ...a]
    }
    return top()
  }
  const normalize = o => Array.isArray(o) ? o.map(normalize) : newtoken(o.code, o.filename, o.lineno, o.column)
  return normalize(compose([...tokenize()]))
}

const parse = (program, filename="") => {
  function* tokenize() {
    let lineno = 1
    let column = 0
    for (const code of program.split(/([()]|[^\n ()]+)/)) {
      if (code.trim()) {
        yield newtoken(code, filename, lineno, column)
        column += code.length
      } else if (/^[ \r\n\t#;]/.test(code) || code === "") {
        lineno += code.split(/\n|;/).length - 1
        if (code.includes("\n")) {
          column = code.split(/\n/).at(-1).length
        }
      }
    }
  }
  const compose = ([t, ...ts], acc=[]) =>
    !t ? acc :
    t.code === ")" ? [acc, compose([ts])] :
    t.code === "(" ? (([x, rest]) => compose(rest, acc.concat([x])))(compose(ts)) :
    compose(ts, acc.concat(t))
  return compose([...tokenize()])
}

class TypeError extends Error { }

const infer = root => {
  let varId = 0
  const newtype = (name, types=[]) => ({name, types})
  const newvar = () => ({...newtype(varId++), var: true})
  const newfn = (types) => newtype("fn", types)
  const newstruct = (name, types) => ({...newfn(types.slice(0, -1).concat([{...types.at(-1), struct: name}])), struct: name})
  const newtuple = types => newtype("tuple", types)
  const newnew = fields => ({...newtype("new" + fields.map(a => "__" + a.code).join(""), fields.map(a => a.type)), fields})
  const newvec = t => newtype("vec", [t])
  const newset = t => newtype("set", [t])
  const newmap = (k, v) => newtype("map", [k, v])

  const marks = (t, mark) => !mark ? t : mark.includes("*") ? ({...newvec(t), mark}) : ({...t, mark})
  const property = (t, name) => (t.props ||= {}, t.props[name] = newvar())

  const faketoken = (s, type) => ({...newtoken(s, "buildin"), type})
  const prune = x => x.instance ? x.instance = prune(x.instance) : x
  const tvoid = newtype("struct{}")
  const tbool = newtype("bool")
  const tint = newtype("int")
  const tfloat = newtype("float64")
  const tstring = newtype("string")
  const terror = newtype("error")
  const tbytes = newtype("bytes")
  const trequest = {...newnew([
    faketoken("scheme", tstring),
    faketoken("method", tstring),
    faketoken("path", tstring),
    faketoken("version", tstring),
    faketoken("host", tstring),
    faketoken("ip", tstring),
  ]), struct: "__io_request"}
  const tresponse = {...newnew([
    faketoken("text", newfn([tstring])),
    faketoken("header", newfn([tstring, tstring])),
    faketoken("cookie", newfn([tstring, tstring])),
  ]), struct: "__io_response"}
  const trequestinit = {...newnew([
    faketoken("method", tstring),
    faketoken("headers", newmap(tstring, newvec(tstring))),
    faketoken("body", tbytes),
  ]), struct: "__io_request_init"}
  const tresponseinit = {...newnew([
    faketoken("status", tint),
    faketoken("headers", newmap(tstring, newvec(tstring))),
    faketoken("blob", tbytes),
    faketoken("json", tbytes),
    faketoken("html", tstring),
    faketoken("text", tstring),
  ]), struct: "__io_response_init"}
  const tio = newtype("io")
  const tv1 = newvar()
  const tv2 = newvar()
  const env = {
    "!": newfn([tbool, tbool]),
    "return": newfn([tv1, tv1]),
    "if": newfn([tbool, tv1, marks(tv2, "?"), tvoid]),
    "iif": newfn([tbool, tv1, tv1, tv1]),
    "throw": newfn([tv1, tv1]),
    "catch": newfn([tv1, newfn([terror, tv1]), tv1]),
    "while": newfn([tbool, tv1, tvoid]),
    "bool": tbool,
    "int": tint,
    "float": tfloat,
    "string": tstring,
    "io": tio,
    "bytes": tbytes,
    "async": newfn([tv1, tvoid]),
    "continue": tvoid,
    "break": tvoid,
  }

  const method = (t, field) =>
    t.var ? property(t, field) :
    t.name === "tuple" && field < t.types.length ? t.types[field] :
    t.name === "error" && field === "message" ? tstring :
    t.name === "io" && field === "sleep" ? newfn([tfloat, tvoid]) :
    t.name === "io" && field === "put" ? newfn([newvar(), tint]) :
    t.name === "io" && field === "puts" ? newfn([newvar(), tint]) :
    t.name === "io" && field === "serve" ? newfn([tstring, newfn([trequest, tresponseinit]), tvoid]) :
    t.name === "io" && field === "fetch" ? newfn([tstring, marks(trequestinit, "?"), tresponse]) :
    t.fields?.find(f => f.code === field).type ||
    (() => { throw new TypeError(`No '${field}' in '${t.name}${t.types.length ? `[${t.types}]` : ""}' type`) })()
  const unify = (a, b) => {
    a = prune(a)
    b = prune(b)
    if (a === b) {
      // nothing
    } else if (a.var) {
      a.instance = b
      if (a.props) {
        if (b.var) {
          b.props = {...(b.props||={}), ...a.props}
        } else {
          Object.keys(a.props).map(name => unify(a.props[name], method(b, name)))
        }
      }
    } else if (b.var) {
      unify(b, a)
    } else {
      if (b.struct && !a.struct) {
        [a, b] = [b, a]
      }
      if (a.struct && !b.struct && b.fields) {
        a.fields || log(a)
        if (!b.fields.every(bf => a.fields.find(af => bf.code === af.code && (unify(bf.type, af.type), true)))) {
          throw new TypeError(`Struct ${a.struct}(${JSON.stringify(a.fields)}) != ${JSON.stringify(b.fields)}`)
        }
        b.instance = a
        return
      }
      if (a.name !== b.name) {
        throw new TypeError(`Type name ${a.name} != ${b.name}`)
      }
      if (a.types.length !== b.types.length) {
        throw new TypeError(`Type args ${JSON.stringify(a.types)} != ${JSON.stringify(b.types)}`)
      }
      a.types.map((x, i) => unify(x, b.types[i]))
    }
  }
  const safeUnify = (a, b) => {
    try {
      unify(a, b)
      return true
    } catch (e) {
      if (e instanceof TypeError) {
        return false
      } else {
        throw e
      }
    }
  }
  const apply = (f, args) => {
    if (f.var) {
      return (f.instance = newfn([...args, newvar()])).types.at(-1)
    }
    let i = 0
    for (const fa of f.types.slice(0, -1)) {
      if (fa.mark?.includes("*")) {
        while (args[i]) {
          if (!safeUnify(fa.types[0], args[i++])) {
            i--
            break
          }
        }
      } else if (fa.mark?.includes("?")) {
        if (args[i]) {
          safeUnify(fa, args[i++])
        }
      } else if (args[i]) {
        unify(fa, args[i++])
      } else {
        throw new TypeError(`No argument ${JSON.stringify(fa)} at ${i} of ${JSON.stringify(f.types)}`)
      }
    }
    if (i !== args.length) {
      throw new TypeError(`Remain ${JSON.stringify(args.slice(i))}} of ${JSON.stringify(f.types)}`)
    }
    return f.types.at(-1)
  }
  const fresh = (type, nonGeneric) => {
    const d = {}
    const rec = t => {
      const u = prune(t)
      return u.var ?
        (nonGeneric.includes(u.name) ? u : d[u.name] ||= marks(newvar(), u.mark)) :
        (v => (v.types.length && type.generics.push(v.types), v))({...u, types: u.types.map(rec)})
    }
    type.generics ||= []
    return rec(type)
  }
  const returnType = a => Array.isArray(a) ? (a.find(x => x[0]?.code === "return")?.[1]?.type || a.reduce((acc, x) => acc || returnType(x), null)) : tvoid
  const infWith = (top, env, nonGeneric) => {
    const inf = node => node.type ||= _inf(node)
    const _inf = node => {
      if (Array.isArray(node)) {
        const head = node[0]
        const tail = node.slice(1)
        if (Array.isArray(head)) {
          return apply(inf(head), tail.map(inf))
        } else {
          const s = head.code
          if (s === "do") {
            tail.map(inf)
            return returnType(tail)
          } else if (s === "struct") {
            const [t, generics, ...ts] = tail
            const gargs = generics.map((t, i) => [t.code, t.type = newvar()])
            const args = range(ts.length / 2).map(i => (ts[i*2].type = infWith(ts[i*2+1], {...env, ...Object.fromEntries(gargs)}, nonGeneric.concat(gargs.map(a => a[1].name))), ts[i*2]))
            return env[t.code] = newstruct(t.code, args.map(a => a.type).concat(newnew(args)))
          } else if (s === "fn") {
            const targs = tail.slice(0, -1).map(_ => newvar())
            const args = tail.slice(0, -1).map((t, i) => [t.code, t.type = marks(targs[i], t.mark)])
            const body = infWith(tail.at(-1), {...env, ...Object.fromEntries(args)}, nonGeneric.concat(targs.map(t => t.name)))
            return newfn([...args.map(a => a[1]), body], tail.slice(0, -1), tail.at(-1))
          } else if (s === "for") {
            tail[0].type = tint
            tail.slice(1, 1).map(node => unify(tint, inf(node)))
            infWith(tail.at(-1), {...env, ...{[tail[0].code]: tint}}, nonGeneric)
            return tvoid
          } else if (s === "each") {
            tail[0].type = newvar()
            tail[1].type = newvar()
            tail.slice(2, -1).map(inf)
            infWith(tail.at(-1), {...env, ...{[tail[0].code]: tail[0].type, [tail[1].code]: tail[1].type}}, nonGeneric)
            return tvoid
          } else if (s === "map") {
            const keys = range(tail.length / 2).map(i => inf(tail[i*2]))
            const values = range(tail.length / 2).map(i => inf(tail[i*2+1]))
            return newmap(keys[0] || newvar(), values[0] || newvar())
          } else if ("+-*/%^=<>!".includes(s[0])) {
            const t = same(tail.map(inf))
            return "== != < > >= <=".split(" ").includes(s) ? tbool : t
          } else if (s === ".") {
            const target = inf(tail[0])
            if (target.name === "tuple") {
              return target.types[tail[1].code]
            } else {
              tail.slice(2).map(inf)
              return method(target, tail[1].code)
            }
          } else if (s === "let") {
            return env[tail[0].code] = inf(tail[1])
          } else if (s === "tuple") {
            return newtuple(tail.map(inf))
          } else if (s === "new") {
            return newnew(range(tail.length / 2).map(i => (tail[i*2].type = inf(tail[i*2+1]), tail[i*2])))
          } else if (s === "vec") {
            return newvec(same(tail.map(inf)))
          } else if (s === "set") {
            return newset(same(tail.map(inf)))
          } else if (s === "||" || s === "&&") {
            return unify(tbool, same(tail.map(inf)))
          } else {
            const argv = tail.map(inf)
            const key = safeJson({code: head.code, argv})
            const ret = apply(inf(head), argv)
            const cache = env.cache ||= {}
            if (key in cache) {
              unify(ret, cache[key])
            } else {
              cache[key] = ret
            }
            return ret
          }
        }
      } else {
        const s = node.code
        return /^[0-9]+\./.test(s)      ? tfloat :
          /^[0-9]+/.test(s)             ? tint :
          s === "true" || s === "false" ? tbool :
          s.startsWith('"')             ? tstring :
          s in env ? fresh(env[s], nonGeneric) :
          (() => { throw new Error(`Type literal '${s}'`) })()
      }
    }
    const same = ([t, ...xs]) => t ? (xs.map(x => unify(t, x)), t) : newvar()
    return inf(top)
  }
  const safeJson = o => {
    const seen = new Set()
    return JSON.stringify(o, (key, value) =>
      typeof value === "object" && value !== null ?
      (seen.has(value) ? seen.size : (seen.add(value), value)) :
      value)
  }

  const copy = t => ({...prune(t), mark: t.mark})
  const fix = node => {
    if (Array.isArray(node)) {
      node.map(fix)
    }
    if (node.type) {
      node.type = copy(node.type)
      node.type.types = node.type.types.map(copy)
      if (node.type.generics) {
        const d = {}
        for (const a of node.type.generics) {
          const t = a.map(prune)
          d[safeJson(t)] ||= t
        }
        node.type.generics = Object.values(d)
      }
    }
  }

  root.map(node => infWith(node, env, [tv1.name]))
  root.map(fix)
  return root
}

const generate = root => {
  const defs = []
  const genreturn = x => {
    const ret = generate([x])
    defs.push(ret.def)
    return x[0]?.code === "do" ? ret.body : `return ${ret.body}`
  }
  const gengeneric = t => t.types.length === 0 && t.var ? "__" + t.name : gentype(t)
  const gentype = t =>
    t.name === "bytes" ? "[]byte" :
    t.types.length === 0 ? (t.var ? "any" : t.name) :
    t.name === "tuple" ? `__${t.name}${t.types.length}[${t.types.map(gentype)}]` :
    t.name.startsWith("new__") ? gennew([], t) :
    t.name === "vec" ? "[]" + gentype(t.types[0]) :
    t.name === "map" ? "map[" + gentype(t.types[0]) + "]" + gentype(t.types[1]) :
    `${t.name}[${t.types.map(gentype)}]`
  const genstruct = (a, t) => (a.length ? `[${a.map(u => gengeneric(u.type) + " any")}] ` : "") + `struct { ${t.fields.map(f => `${f.code} ${gengeneric(f.type)}`).join("\n")} }`
  const gennew = (a, t) =>
    t.struct ? t.struct + (a.length ? `[${a.map(u => gengeneric(u.type) + " any")}] ` : "") :
    genstruct(a, t)
  const genfunc = (x, t, name="") => `func ${name}(${x.slice(1, -1).map(y => `${y.code} ${gentype(y.type)}`)}) ${gentype(x.type.types.at(-1))}`
  const genfor = ([a, b, c, d, e]) => `for ${a} := ${b}; ${a} < ${c}; ${a} += ${d} { ${e} }`
  const genlet = (body, id) => body[0]?.code === "fn" ?
    body.type.generics.map(a => {
      const x = structuredClone(body)
      x.type = {...x.type, types: a}
      x.slice(1, -1).map((arg, i) => arg.type = a[i])
      return `${id}__${a.map(gentype).join("__")} := ${gen(x)}`
    }).join("\n") :
    `${id} := ${gen(body)}`
  const errinfo = x => Array.isArray(x) ? errinfo(x[0]) : [JSON.stringify(x.filename), x.lineno, x.column]
  const genhead = x => x.type.name === "fn" && x.type.generics?.length ?
    `${gen(x)}__${x.type.types.map(gentype).join("__")}` :
    gen(x)
  const gen = x => !Array.isArray(x) ? x.code :
    x[0].code === "do"     ? x.slice(1).map(gen).join("\n") :
    x[0].code === "for"    ? genfor(x.slice(1).map(gen)) :
    x[0].code === "each"   ? `for ${x[1].code}, ${x[2].code} := range ${gen(x[3])} { ${gen(x[4])} }` :
    x[0].code === "while"  ? `for ${gen(x[1])} { ${gen(x[2])} }` :
    x[0].code === "let"    ? genlet(x[2], x[1].code) :
    x[0].code === "return" ? `return ${gen(x[1])}` :
    x[0].code === "throw"  ? `panic(MoaError{${gen(x[1])}, ${errinfo(x[1])}})` :
    x[0].code === "catch"  ? `func() (__ret ${gentype(x[1].type)}) {
		defer func() {
			r := recover()
			if r != nil {
				if v, ok := r.(error); ok {
					__ret = ${gen(x[2])}(v)
				} else {
					panic(r)
				}
			}
		}()
    __ret = ${gen(x[1])}
    return
  }()` :
    x[0].code === "async"  ? `go func() { ${gen(x[1])} }()` :
    x[0].code === "if"     ? `if ${gen(x[1])} { ${gen(x[2])} }` + (x[3] ? ` else { ${gen(x[3])} }` : "") :
    x[0].code === "iif"    ? `func () ${gentype(x[2].type)} { if ${gen(x[1])} { return ${gen(x[2])} } else { return ${gen(x[3])} } }()` :
    x[0].code === "struct" ? (defs.push(`type ${x[1].code} ${genstruct(x[2], x.type.types.at(-1))}`), "") :
    x[0].code === "fn"     ? `${genfunc(x)} { ${genreturn(x.at(-1))} }` :
    x[0].code === "tuple"  ? `__tuple${x.length - 1}[${x.slice(1).map(node => gentype(node.type))}]{ ${x.slice(1).map(gen)} }` :
    x[0].code === "new"    ? `${gennew([], x.type)}{${range((x.length-1)/2).map(i => x[i*2+1].code + ":" + gen(x[i*2+2]))}}` :
    x[0].code === "vec"    ? `[]${gentype(x.type.types[0])}{ ${x.slice(1).map(gen)} }` :
    x[0].code === "map"    ? `map[${gentype(x.type.types[0])}]${gentype(x.type.types[1])}{ ${range((x.length-1)/2).map(i => `${gen(x[i*2+1])}: ${gen(x[i*2+2])}`)} }` :
    x[0].code === "set"    ? `map[${gentype(x.type.types[0])}]struct{}{ ${x.slice(1).map(n => `${gen(n)}: struct{}{}`)} }` :
    x[0].type?.struct      ? gen(x[0]) + (x[0].type.types.at(-1).types.find(t => t.var) ? `[${x[0].type.types.slice(0, -1).map(gentype)}]` : "")+ "{" + x.slice(1).map(gen).join(", ") + "}" :
    x[0].code === "." && x[1].code === "io" ? `__io_${x[2].code}` :
    x[0].code === "." && x[1]?.type?.name === "tuple" ? `${gen(x[1])}.v${x[2].code}` :
    x[0].code === "." && x[1]?.type?.name === "error" && x[2].code === "message" ? `${gen(x[1])}.Error()` :
    /[+\-*/%^<>!=|&.]/.test(x[0].code) ? (x.length === 3 ? gen(x[1]) + x[0].code + gen(x[2]) : x[0].code + gen(x[1])) :
    genhead(x[0]) + "(" + x.slice(1).map(gen).join(", ") + ")"
  const body = root.map(gen).join("\n")
  return {
    def: defs.join("\n"),
    body,
  }
}


const execGo = cmd => {
  const fs = require("fs")
  const {execSync} = require("child_process")
  const files = process.argv.length === 3 ? fs.globSync("**/*.moa") : process.argv.slice(3)
  const runtime = fs.readFileSync(__dirname + "/runtime.go", "utf-8")
  const compile = (code, filename) => generate(infer(sugar(code, filename)))
  const xs = files.map(path => compile(fs.readFileSync(path, "utf-8"), path))
  const def = xs.map(x => x.def).join("\n")
  const body = xs.map(x => x.body).join("\n")
  const go = `${runtime}\n${def}\nfunc main() { ${body} }`
  fs.writeFileSync("/tmp/a.go", go)
  execSync(`go ${cmd} /tmp/a.go`, {stdio: "inherit"})
}

if (process.argv[2] === "selftest") {
  process.exit(require("./test.js").test({sugar, parse, infer, generate, TypeError}))
} else if (process.argv[2] === "build") {
  execGo("build")
} else if (process.argv[2] === "run") {
  execGo("run")
} else if (process.argv[2] === "repl") {
  console.log("implementing...")
} else if (process.argv[2] === "test") {
  console.log("implementing...")
} else if (process.argv[2] === "version") {
  console.log("moa version 0.0.1")
} else {
  console.log(`Moa is a programming language

Usage: moa <command> [...arguments]

Commands:
  moa build [...files]     compile to an executable file
  moa run   [...files]     compile and run
  moa repl  [...files]     start a shell
  moa test  [...files]     run tests
  moa version              display Moa version`)
}
